os: Visual Studio 2017

before_build:
  - nuget restore src\Renci.SshNet.VS2017.sln

build:
  project: src\Renci.SshNet.VS2017.sln
  verbosity: minimal

test_script:
- cmd: >-
    vstest.console /logger:Appveyor src\Renci.SshNet.Tests\bin\Debug\Renci.SshNet.Tests.dll /TestCaseFilter:"TestCategory!=integration&TestCategory!=LongRunning"

    vstest.console /logger:Appveyor src\Renci.SshNet.Tests.NET35\bin\Debug\Renci.SshNet.Tests.NET35.dll /TestCaseFilter:"TestCategory!=integration&TestCategory!=LongRunning"